### ISSUE TITLE
Example in the README is incorrect

### ISSUE THREAD

**Issue by dnephin** [wroberts/pytimeparse#8]
```python
from pytimeparse import parse
```

I believe this should be

```python
from pytimeparse.timeparse import timeparse
```

**Comment by wroberts** [comment]
Hi @dnephin : Both import statements `workforme` since version 1.1.4 (b7285cd25ca8d230e25f3d22a0efd94560647f5a).  Before that, you're right, the longer import statement was the only one that worked.

**Comment by dnephin** [comment]
Ok, I guess I was on an older versioj
